open Console

//This function divides two passed values and handles possible exceptions
let sum x y = try x / y with
                  InvalidOp m    = writen ("You can't divide these values! " ++ m)
                  DivideByZero m = writen ("Ooop, division by zero! " ++ m)

sum 2 "0" $ //This will cause InvalidOp error
sum 2 0 //This will cause DivideByZero error